apiVersion: v1
kind: Service
metadata:
  name: json2html
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: json2html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json2html
spec:
  selector:
    matchLabels:
      app: json2html
  replicas: 1
  template:
    metadata:
      labels:
        app: json2html
    spec:
      containers:
      - name: json2html
        image: bloopletech/json2html@sha256:91831fb1b8e1703546650ebba587227dee2b7e4377478e4faeb0cf7eda0648fb
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "64Mi"
      imagePullSecrets:
      - name: regcred
