apiVersion: v1
kind: Service
metadata:
  name: json2html
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: json2html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json2html
spec:
  selector:
    matchLabels:
      app: json2html
  replicas: 1
  template:
    metadata:
      labels:
        app: json2html
    spec:
      containers:
      - name: json2html
        image: bloopletech/json2html@sha256:bba3089e672ce262311d75d80fd0c39e3535187942972990b6b6541417b7a3ae
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "64Mi"
      imagePullSecrets:
      - name: regcred
