apiVersion: v1
kind: Service
metadata:
  name: json2html
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: json2html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json2html
spec:
  selector:
    matchLabels:
      app: json2html
  replicas: 1
  template:
    metadata:
      labels:
        app: json2html
    spec:
      containers:
      - name: json2html
        image: bloopletech/json2html@sha256:b045456137672ddbd861c4784758838ab509b55ec09caf8f48382bef11e7ddbd
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "32Mi"
      imagePullSecrets:
      - name: regcred
