apiVersion: v1
kind: Service
metadata:
  name: json2html
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: json2html
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: json2html
spec:
  selector:
    matchLabels:
      app: json2html
  replicas: 1
  template:
    metadata:
      labels:
        app: json2html
    spec:
      containers:
      - name: json2html
        image: bloopletech/json2html@sha256:d868164cb4f459454b92df2fb0911e36175d2189ef4b26d68ff9452fdd9ea79c
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "64Mi"
      imagePullSecrets:
      - name: regcred
